import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "./providers/convex-client-provider";
import { NavBar } from "@/components/navbar";
import BarProviders from "@/components/bar-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BarProviders>
          <ConvexClientProvider>
            <NavBar />
            {children}
          </ConvexClientProvider>
        </BarProviders>
      </body>
    </html>
  );
}
